# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ios-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-app
  pod 'AFNetworking', '~> 4.0'
end
