/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.2/samples
 */

buildscript {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
    dependencies {
        classpath(libs.kotlin.stdlib)
        classpath("gradle:build-logic")
    }
}

allprojects {
    plugins.withType(com.android.build.gradle.BasePlugin::class) {
        extensions.configure(com.android.build.gradle.BaseExtension::class) {
            compileSdkVersion(30)
            defaultConfig {
                minSdk = 16
            }
        }
    }
}

tasks.create("hello") {
    println("$name configure")

    group = "my"

    doFirst {
        println("$name execute")
    }
}

val hello2 = tasks.register("hello2") {
    println("$name configure")

    group = "my"

    doFirst {
        println("$name execute 1")
    }
    doLast {
        println("$name execute 2")
    }
}

hello2.configure {
    doLast {
        println("$name execute 0")
    }
}
